# Generated by Django 5.2.1 on 2025-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('local', 'Local'), ('cochera', 'Cochera'), ('departamento', 'Departamento')], max_length=50)),
                ('metros_cuadrados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_huespedes', models.IntegerField(default=2)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('no disponible', 'No disponible')], max_length=50)),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
