# Generated by Django 5.2.1 on 2025-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='cantidad_huespedes',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_diario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
