# Generated by Django 5.2.1 on 2025-05-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0003_alter_inmueble_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='propietario',
        ),
    ]
