# Generated by Django 5.2 on 2025-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0004_remove_inmueble_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('no disponible', 'No disponible')], max_length=50),
        ),
    ]
