# Generated by Django 5.2.1 on 2025-06-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_alter_inmueble_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
