# Generated by Django 5.2.1 on 2025-06-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0006_inmueble_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_fin_inactividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_inicio_inactividad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
