# Generated by Django 5.2.1 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0007_inmueble_fecha_fin_inactividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('No disponible', 'No disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Local', 'Local'), ('Cochera', 'Cochera'), ('Departamento', 'Departamento')], max_length=50),
        ),
    ]
