# Generated by Django 5.2.1 on 2025-06-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0008_inmueble_foto_alter_inmueble_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='banos',
            field=models.IntegerField(default=2),
        ),
    ]
