# Generated by Django 5.2.1 on 2025-06-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0009_inmueble_banos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='banos',
            new_name='baños',
        ),
    ]
