# Generated by Django 5.2.1 on 2025-06-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0010_rename_banos_inmueble_baños'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
