# Generated by Django 5.2 on 2025-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0011_alter_inmueble_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='minimo_dias_reserva',
            field=models.IntegerField(default=1),
        ),
    ]
