# Generated by Django 5.2 on 2025-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0012_inmueble_minimo_dias_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='maximo_dias_reserva',
            field=models.IntegerField(default=30),
        ),
    ]
