# Generated by Django 5.2.1 on 2025-07-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0013_inmueble_maximo_dias_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=3),
        ),
    ]
