# Generated by Django 5.2.1 on 2025-07-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0015_remove_inmueble_calificacion_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='baños',
            new_name='banos',
        ),
    ]
