# Generated by Django 5.2.2 on 2025-07-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0016_rename_baños_inmueble_banos'),
        ('inmueble', '0016_reseña'),
    ]

    operations = [
    ]
