# Generated by Django 5.2.2 on 2025-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0017_merge_0016_rename_baños_inmueble_banos_0016_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='estrellas',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=3),
        ),
    ]
