# Generated by Django 5.2.1 on 2025-07-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0017_merge_0016_rename_baños_inmueble_banos_0016_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='devolucion_2_a_0dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='devolucion_7_a_2dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='devolucion_7dias_o_mas',
            field=models.IntegerField(default=0),
        ),
    ]
