# Generated by Django 5.2.1 on 2025-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0018_inmueble_devolucion_2_a_0dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='devolucion_2_a_0dias',
            field=models.IntegerField(),
        ),
    ]
