# Generated by Django 5.2.2 on 2025-07-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0018_inmueble_estrellas'),
        ('inmueble', '0020_alter_inmueble_devolucion_2_a_0dias'),
    ]

    operations = [
    ]
