# Generated by Django 5.2.1 on 2025-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='pepe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default=2222222, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
