# Generated by Django 5.2.1 on 2025-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_apellido_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('inquilino', 'Inquilino'), ('Empleado', 'Empleado')], max_length=50),
        ),
    ]
