# Generated by Django 5.2.1 on 2025-06-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Inquilino', 'Inquilino'), ('Empleado', 'Empleado')], default='Inquilino', max_length=20),
        ),
    ]
