# Generated by Django 5.2.1 on 2025-07-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('inquilino', 'Inquilino'), ('empleado', 'Empleado')], default='Inquilino', max_length=20),
        ),
    ]
