# Generated by Django 5.2.1 on 2025-05-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha_solicitud',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
