# Generated by Django 5.2.1 on 2025-05-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudreserva',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True),
        ),
    ]
