# Generated by Django 5.2 on 2025-05-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendiente de pago', 'Pendiente de pago')], default='pendiente', max_length=50),
        ),
    ]
