# Generated by Django 5.2 on 2025-05-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_solicitudreserva_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
