# Generated by Django 5.2.1 on 2025-06-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_solicitudreserva_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquilinos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='inquilinos',
            field=models.ManyToManyField(to='reservas.inquilino'),
        ),
    ]
