# Generated by Django 5.2.1 on 2025-06-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_tarjetapago_titular_alter_solicitudreserva_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetapago',
            name='titular',
        ),
        migrations.AddField(
            model_name='solicitudreserva',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tarjetapago',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
