# Generated by Django 5.2.2 on 2025-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_remove_tarjetapago_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudreserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pendiente de pago', 'Pendiente de Pago'), ('pagada', 'Pagada'), ('confirmada', 'Confirmada'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50),
        ),
    ]
